# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from . import outputs

import types

__config__ = pulumi.Config('mssql')


class _ExportableConfig(types.ModuleType):
    @property
    def azure_auth(self) -> Optional[str]:
        """
        When provided, Azure AD authentication will be used when connecting.
        """
        return __config__.get('azureAuth')

    @property
    def hostname(self) -> Optional[str]:
        """
        FQDN or IP address of the SQL endpoint. Can be also set using `MSSQL_HOSTNAME` environment variable.
        """
        return __config__.get('hostname') or _utilities.get_env('MSSQL_HOSTNAME')

    @property
    def port(self) -> int:
        """
        TCP port of SQL endpoint. Defaults to `1433`. Can be also set using `MSSQL_PORT` environment variable.
        """
        return __config__.get_int('port') or (_utilities.get_env_int('MSSQL_PORT') or 1433)

    @property
    def sql_auth(self) -> Optional[str]:
        """
        When provided, SQL authentication will be used when connecting.
        """
        return __config__.get('sqlAuth')

