// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Mssql
{
    public static class GetSqlUsers
    {
        /// <summary>
        /// Obtains information about all SQL users found in a database
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Mssql = Pulumi.Mssql;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var master = Mssql.GetDatabase.Invoke(new()
        ///     {
        ///         Name = "master",
        ///     });
        /// 
        ///     var example = Mssql.GetSqlUsers.Invoke(new()
        ///     {
        ///         DatabaseId = master.Apply(getDatabaseResult =&gt; getDatabaseResult.Id),
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["users"] = example.Apply(getSqlUsersResult =&gt; getSqlUsersResult.Users),
        ///     };
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetSqlUsersResult> InvokeAsync(GetSqlUsersArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSqlUsersResult>("mssql:index/getSqlUsers:getSqlUsers", args ?? new GetSqlUsersArgs(), options.WithDefaults());

        /// <summary>
        /// Obtains information about all SQL users found in a database
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Mssql = Pulumi.Mssql;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var master = Mssql.GetDatabase.Invoke(new()
        ///     {
        ///         Name = "master",
        ///     });
        /// 
        ///     var example = Mssql.GetSqlUsers.Invoke(new()
        ///     {
        ///         DatabaseId = master.Apply(getDatabaseResult =&gt; getDatabaseResult.Id),
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["users"] = example.Apply(getSqlUsersResult =&gt; getSqlUsersResult.Users),
        ///     };
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetSqlUsersResult> Invoke(GetSqlUsersInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSqlUsersResult>("mssql:index/getSqlUsers:getSqlUsers", args ?? new GetSqlUsersInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSqlUsersArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// ID of database. Can be retrieved using `mssql.Database` or `SELECT DB_ID('&lt;db_name&gt;')`. Defaults to ID of `master`.
        /// </summary>
        [Input("databaseId")]
        public string? DatabaseId { get; set; }

        public GetSqlUsersArgs()
        {
        }
        public static new GetSqlUsersArgs Empty => new GetSqlUsersArgs();
    }

    public sealed class GetSqlUsersInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// ID of database. Can be retrieved using `mssql.Database` or `SELECT DB_ID('&lt;db_name&gt;')`. Defaults to ID of `master`.
        /// </summary>
        [Input("databaseId")]
        public Input<string>? DatabaseId { get; set; }

        public GetSqlUsersInvokeArgs()
        {
        }
        public static new GetSqlUsersInvokeArgs Empty => new GetSqlUsersInvokeArgs();
    }


    [OutputType]
    public sealed class GetSqlUsersResult
    {
        /// <summary>
        /// ID of database. Can be retrieved using `mssql.Database` or `SELECT DB_ID('&lt;db_name&gt;')`. Defaults to ID of `master`.
        /// </summary>
        public readonly string? DatabaseId;
        /// <summary>
        /// ID of the resource, equals to database ID
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Set of SQL user objects
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSqlUsersUserResult> Users;

        [OutputConstructor]
        private GetSqlUsersResult(
            string? databaseId,

            string id,

            ImmutableArray<Outputs.GetSqlUsersUserResult> users)
        {
            DatabaseId = databaseId;
            Id = id;
            Users = users;
        }
    }
}
