// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Mssql
{
    public static class GetSqlLogins
    {
        /// <summary>
        /// Obtains information about all SQL logins found in SQL Server instance.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Mssql = Pulumi.Mssql;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Mssql.GetSqlLogins.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["databases"] = example.Apply(getSqlLoginsResult =&gt; getSqlLoginsResult.Logins),
        ///     };
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetSqlLoginsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSqlLoginsResult>("mssql:index/getSqlLogins:getSqlLogins", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetSqlLoginsResult
    {
        /// <summary>
        /// ID of the resource used only internally by the provider.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Set of SQL login objects
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSqlLoginsLoginResult> Logins;

        [OutputConstructor]
        private GetSqlLoginsResult(
            string id,

            ImmutableArray<Outputs.GetSqlLoginsLoginResult> logins)
        {
            Id = id;
            Logins = logins;
        }
    }
}
