// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Mssql
{
    /// <summary>
    /// The provider type for the mssql package. By default, resources use package-wide configuration
    /// settings, however an explicit `Provider` instance may be created and passed during resource
    /// construction to achieve fine-grained programmatic control over provider settings. See the
    /// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
    /// </summary>
    [MssqlResourceType("pulumi:providers:mssql")]
    public partial class Provider : global::Pulumi.ProviderResource
    {
        /// <summary>
        /// FQDN or IP address of the SQL endpoint. Can be also set using `MSSQL_HOSTNAME` environment variable.
        /// </summary>
        [Output("hostname")]
        public Output<string?> Hostname { get; private set; } = null!;


        /// <summary>
        /// Create a Provider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Provider(string name, ProviderArgs? args = null, CustomResourceOptions? options = null)
            : base("mssql", name, args ?? new ProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse/pulumi-mssql",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ProviderArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// When provided, Azure AD authentication will be used when connecting.
        /// </summary>
        [Input("azureAuth", json: true)]
        public Input<Inputs.ProviderAzureAuthArgs>? AzureAuth { get; set; }

        /// <summary>
        /// FQDN or IP address of the SQL endpoint. Can be also set using `MSSQL_HOSTNAME` environment variable.
        /// </summary>
        [Input("hostname")]
        public Input<string>? Hostname { get; set; }

        /// <summary>
        /// TCP port of SQL endpoint. Defaults to `1433`. Can be also set using `MSSQL_PORT` environment variable.
        /// </summary>
        [Input("port", json: true)]
        public Input<int>? Port { get; set; }

        /// <summary>
        /// When provided, SQL authentication will be used when connecting.
        /// </summary>
        [Input("sqlAuth", json: true)]
        public Input<Inputs.ProviderSqlAuthArgs>? SqlAuth { get; set; }

        public ProviderArgs()
        {
            Hostname = Utilities.GetEnv("MSSQL_HOSTNAME");
            Port = Utilities.GetEnvInt32("MSSQL_PORT") ?? 1433;
        }
        public static new ProviderArgs Empty => new ProviderArgs();
    }
}
