// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Mssql
{
    /// <summary>
    /// Grants server-level permission.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Mssql = Pulumi.Mssql;
    /// using Mssql = Pulumiverse.Mssql;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = Mssql.GetSqlLogin.Invoke(new()
    ///     {
    ///         Name = "example_login",
    ///     });
    /// 
    ///     var connectToExample = new Mssql.ServerPermission("connectToExample", new()
    ///     {
    ///         PrincipalId = example.Apply(getSqlLoginResult =&gt; getSqlLoginResult.PrincipalId),
    ///         Permission = "CONNECT SQL",
    ///         WithGrantOption = true,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// import using &lt;principal_id&gt;/&lt;permission&gt;
    /// 
    /// ```sh
    /// $ pulumi import mssql:index/serverPermission:ServerPermission example '7/CONNECT SQL'
    /// ```
    /// </summary>
    [MssqlResourceType("mssql:index/serverPermission:ServerPermission")]
    public partial class ServerPermission : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Name of server-level SQL permission. For full list of supported permissions see [docs](https://learn.microsoft.com/en-us/sql/t-sql/statements/grant-server-permissions-transact-sql?view=azuresqldb-current#remarks)
        /// </summary>
        [Output("permission")]
        public Output<string> Permission { get; private set; } = null!;

        /// <summary>
        /// ID of the principal who will be granted `permission`. Can be retrieved using `mssql.ServerRole` or `mssql.SqlLogin`.
        /// </summary>
        [Output("principalId")]
        public Output<string> PrincipalId { get; private set; } = null!;

        /// <summary>
        /// When set to `true`, `principal_id` will be allowed to grant the `permission` to other principals. Defaults to `false`
        /// </summary>
        [Output("withGrantOption")]
        public Output<bool> WithGrantOption { get; private set; } = null!;


        /// <summary>
        /// Create a ServerPermission resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ServerPermission(string name, ServerPermissionArgs args, CustomResourceOptions? options = null)
            : base("mssql:index/serverPermission:ServerPermission", name, args ?? new ServerPermissionArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ServerPermission(string name, Input<string> id, ServerPermissionState? state = null, CustomResourceOptions? options = null)
            : base("mssql:index/serverPermission:ServerPermission", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse/pulumi-mssql",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ServerPermission resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ServerPermission Get(string name, Input<string> id, ServerPermissionState? state = null, CustomResourceOptions? options = null)
        {
            return new ServerPermission(name, id, state, options);
        }
    }

    public sealed class ServerPermissionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of server-level SQL permission. For full list of supported permissions see [docs](https://learn.microsoft.com/en-us/sql/t-sql/statements/grant-server-permissions-transact-sql?view=azuresqldb-current#remarks)
        /// </summary>
        [Input("permission", required: true)]
        public Input<string> Permission { get; set; } = null!;

        /// <summary>
        /// ID of the principal who will be granted `permission`. Can be retrieved using `mssql.ServerRole` or `mssql.SqlLogin`.
        /// </summary>
        [Input("principalId", required: true)]
        public Input<string> PrincipalId { get; set; } = null!;

        /// <summary>
        /// When set to `true`, `principal_id` will be allowed to grant the `permission` to other principals. Defaults to `false`
        /// </summary>
        [Input("withGrantOption")]
        public Input<bool>? WithGrantOption { get; set; }

        public ServerPermissionArgs()
        {
        }
        public static new ServerPermissionArgs Empty => new ServerPermissionArgs();
    }

    public sealed class ServerPermissionState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of server-level SQL permission. For full list of supported permissions see [docs](https://learn.microsoft.com/en-us/sql/t-sql/statements/grant-server-permissions-transact-sql?view=azuresqldb-current#remarks)
        /// </summary>
        [Input("permission")]
        public Input<string>? Permission { get; set; }

        /// <summary>
        /// ID of the principal who will be granted `permission`. Can be retrieved using `mssql.ServerRole` or `mssql.SqlLogin`.
        /// </summary>
        [Input("principalId")]
        public Input<string>? PrincipalId { get; set; }

        /// <summary>
        /// When set to `true`, `principal_id` will be allowed to grant the `permission` to other principals. Defaults to `false`
        /// </summary>
        [Input("withGrantOption")]
        public Input<bool>? WithGrantOption { get; set; }

        public ServerPermissionState()
        {
        }
        public static new ServerPermissionState Empty => new ServerPermissionState();
    }
}
