// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("mssql");

/**
 * When provided, Azure AD authentication will be used when connecting.
 */
export declare const azureAuth: outputs.config.AzureAuth | undefined;
Object.defineProperty(exports, "azureAuth", {
    get() {
        return __config.getObject<outputs.config.AzureAuth>("azureAuth");
    },
    enumerable: true,
});

/**
 * FQDN or IP address of the SQL endpoint. Can be also set using `MSSQL_HOSTNAME` environment variable.
 */
export declare const hostname: string | undefined;
Object.defineProperty(exports, "hostname", {
    get() {
        return __config.get("hostname") ?? utilities.getEnv("MSSQL_HOSTNAME");
    },
    enumerable: true,
});

/**
 * TCP port of SQL endpoint. Defaults to `1433`. Can be also set using `MSSQL_PORT` environment variable.
 */
export declare const port: number;
Object.defineProperty(exports, "port", {
    get() {
        return __config.getObject<number>("port") ?? (utilities.getEnvNumber("MSSQL_PORT") || 1433);
    },
    enumerable: true,
});

/**
 * When provided, SQL authentication will be used when connecting.
 */
export declare const sqlAuth: outputs.config.SqlAuth | undefined;
Object.defineProperty(exports, "sqlAuth", {
    get() {
        return __config.getObject<outputs.config.SqlAuth>("sqlAuth");
    },
    enumerable: true,
});

