// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Mssql.Outputs
{

    [OutputType]
    public sealed class GetSchemasSchemaResult
    {
        /// <summary>
        /// ID of database. Can be retrieved using `mssql.Database` or `SELECT DB_ID('&lt;db_name&gt;')`.
        /// </summary>
        public readonly string DatabaseId;
        /// <summary>
        /// `&lt;database_id&gt;/&lt;schema_id&gt;`. Schema ID can be retrieved using `SELECT SCHEMA_ID('&lt;schema_name&gt;')`.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Schema name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// ID of database role or user owning this schema. Can be retrieved using `mssql.DatabaseRole`, `mssql.SqlUser`, `mssql.AzureadUser` or `mssql.AzureadServicePrincipal`
        /// </summary>
        public readonly string OwnerId;

        [OutputConstructor]
        private GetSchemasSchemaResult(
            string databaseId,

            string id,

            string name,

            string ownerId)
        {
            DatabaseId = databaseId;
            Id = id;
            Name = name;
            OwnerId = ownerId;
        }
    }
}
