// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Mssql.Outputs
{

    [OutputType]
    public sealed class GetSqlUsersUserResult
    {
        /// <summary>
        /// ID of database. Can be retrieved using `mssql.Database` or `SELECT DB_ID('&lt;db_name&gt;')`.
        /// </summary>
        public readonly string DatabaseId;
        /// <summary>
        /// `&lt;database_id&gt;/&lt;user_id&gt;`. User ID can be retrieved using `SELECT DATABASE_PRINCIPAL_ID('&lt;user_name&gt;')`.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// SID of SQL login. Can be retrieved using `mssql.SqlLogin` or `SELECT SUSER_SID('&lt;login_name&gt;')`.
        /// </summary>
        public readonly string LoginId;
        /// <summary>
        /// User name. Cannot be longer than 128 chars.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetSqlUsersUserResult(
            string databaseId,

            string id,

            string loginId,

            string name)
        {
            DatabaseId = databaseId;
            Id = id;
            LoginId = loginId;
            Name = name;
        }
    }
}
