// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Returns all permissions granted in a DB to given principal
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as mssql from "@pulumi/mssql";
 *
 * const exampleDatabase = mssql.getDatabase({
 *     name: "example",
 * });
 * const exampleSqlUser = exampleDatabase.then(exampleDatabase => mssql.getSqlUser({
 *     name: "example_user",
 *     databaseId: exampleDatabase.id,
 * }));
 * const exampleDatabasePermissions = exampleSqlUser.then(exampleSqlUser => mssql.getDatabasePermissions({
 *     principalId: exampleSqlUser.id,
 * }));
 * export const permissions = exampleDatabasePermissions.then(exampleDatabasePermissions => exampleDatabasePermissions.permissions);
 * ```
 */
export function getDatabasePermissions(args: GetDatabasePermissionsArgs, opts?: pulumi.InvokeOptions): Promise<GetDatabasePermissionsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("mssql:index/getDatabasePermissions:getDatabasePermissions", {
        "principalId": args.principalId,
    }, opts);
}

/**
 * A collection of arguments for invoking getDatabasePermissions.
 */
export interface GetDatabasePermissionsArgs {
    /**
     * `<database_id>/<principal_id>`. Can be retrieved using `mssql.DatabaseRole`, `mssql.SqlUser`, `mssql.AzureadUser` or `mssql.AzureadServicePrincipal`.
     */
    principalId: string;
}

/**
 * A collection of values returned by getDatabasePermissions.
 */
export interface GetDatabasePermissionsResult {
    /**
     * `<database_id>/<principal_id>`.
     */
    readonly id: string;
    /**
     * Set of permissions granted to the principal
     */
    readonly permissions: outputs.GetDatabasePermissionsPermission[];
    /**
     * `<database_id>/<principal_id>`. Can be retrieved using `mssql.DatabaseRole`, `mssql.SqlUser`, `mssql.AzureadUser` or `mssql.AzureadServicePrincipal`.
     */
    readonly principalId: string;
}
/**
 * Returns all permissions granted in a DB to given principal
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as mssql from "@pulumi/mssql";
 *
 * const exampleDatabase = mssql.getDatabase({
 *     name: "example",
 * });
 * const exampleSqlUser = exampleDatabase.then(exampleDatabase => mssql.getSqlUser({
 *     name: "example_user",
 *     databaseId: exampleDatabase.id,
 * }));
 * const exampleDatabasePermissions = exampleSqlUser.then(exampleSqlUser => mssql.getDatabasePermissions({
 *     principalId: exampleSqlUser.id,
 * }));
 * export const permissions = exampleDatabasePermissions.then(exampleDatabasePermissions => exampleDatabasePermissions.permissions);
 * ```
 */
export function getDatabasePermissionsOutput(args: GetDatabasePermissionsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDatabasePermissionsResult> {
    return pulumi.output(args).apply((a: any) => getDatabasePermissions(a, opts))
}

/**
 * A collection of arguments for invoking getDatabasePermissions.
 */
export interface GetDatabasePermissionsOutputArgs {
    /**
     * `<database_id>/<principal_id>`. Can be retrieved using `mssql.DatabaseRole`, `mssql.SqlUser`, `mssql.AzureadUser` or `mssql.AzureadServicePrincipal`.
     */
    principalId: pulumi.Input<string>;
}
