// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Obtains information about single server role.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as mssql from "@pulumi/mssql";
 *
 * const byName = mssql.getServerRole({
 *     name: "example",
 * });
 * const byId = mssql.getServerRole({
 *     id: "8",
 * });
 * ```
 */
export function getServerRole(args?: GetServerRoleArgs, opts?: pulumi.InvokeOptions): Promise<GetServerRoleResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("mssql:index/getServerRole:getServerRole", {
        "id": args.id,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getServerRole.
 */
export interface GetServerRoleArgs {
    /**
     * ID of the member principal
     */
    id?: string;
    /**
     * Name of the server principal
     */
    name?: string;
}

/**
 * A collection of values returned by getServerRole.
 */
export interface GetServerRoleResult {
    /**
     * Role principal ID. Either `name` or `id` must be provided.
     */
    readonly id: string;
    /**
     * Set of role members
     */
    readonly members: outputs.GetServerRoleMember[];
    /**
     * Role name. Must follow [Regular Identifiers rules](https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers#rules-for-regular-identifiers) and cannot be longer than 128 chars. Either `name` or `id` must be provided.
     */
    readonly name: string;
    /**
     * ID of another server role or login owning this role. Can be retrieved using `mssql.ServerRole` or `mssql.SqlLogin`.
     */
    readonly ownerId: string;
}
/**
 * Obtains information about single server role.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as mssql from "@pulumi/mssql";
 *
 * const byName = mssql.getServerRole({
 *     name: "example",
 * });
 * const byId = mssql.getServerRole({
 *     id: "8",
 * });
 * ```
 */
export function getServerRoleOutput(args?: GetServerRoleOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetServerRoleResult> {
    return pulumi.output(args).apply((a: any) => getServerRole(a, opts))
}

/**
 * A collection of arguments for invoking getServerRole.
 */
export interface GetServerRoleOutputArgs {
    /**
     * ID of the member principal
     */
    id?: pulumi.Input<string>;
    /**
     * Name of the server principal
     */
    name?: pulumi.Input<string>;
}
