// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Obtains information about single SQL login.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as mssql from "@pulumi/mssql";
 *
 * const sa = mssql.getSqlLogin({
 *     name: "sa",
 * });
 * export const id = sa.then(sa => sa.id);
 * export const dbId = sa.then(sa => sa.defaultDatabaseId);
 * ```
 */
export function getSqlLogin(args: GetSqlLoginArgs, opts?: pulumi.InvokeOptions): Promise<GetSqlLoginResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("mssql:index/getSqlLogin:getSqlLogin", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getSqlLogin.
 */
export interface GetSqlLoginArgs {
    /**
     * Login name. Must follow [Regular Identifiers rules](https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers#rules-for-regular-identifiers) and cannot contain `\`
     */
    name: string;
}

/**
 * A collection of values returned by getSqlLogin.
 */
export interface GetSqlLoginResult {
    /**
     * When `true`, password expiration policy is enforced for this login.
     */
    readonly checkPasswordExpiration: boolean;
    /**
     * When `true`, the Windows password policies of the computer on which SQL Server is running are enforced on this login.
     */
    readonly checkPasswordPolicy: boolean;
    /**
     * ID of login's default DB. The ID can be retrieved using `mssql.Database` data resource.
     */
    readonly defaultDatabaseId: string;
    /**
     * Default language assigned to login.
     */
    readonly defaultLanguage: string;
    /**
     * Login SID. Can be retrieved using `SELECT SUSER_SID('<login_name>')`.
     */
    readonly id: string;
    /**
     * When true, password change will be forced on first logon.
     */
    readonly mustChangePassword: boolean;
    /**
     * Login name. Must follow [Regular Identifiers rules](https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers#rules-for-regular-identifiers) and cannot contain `\`
     */
    readonly name: string;
    /**
     * ID used to reference SQL Login in other resources, e.g. `serverRole`. Can be retrieved from `sys.sql_logins`.
     */
    readonly principalId: string;
}
/**
 * Obtains information about single SQL login.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as mssql from "@pulumi/mssql";
 *
 * const sa = mssql.getSqlLogin({
 *     name: "sa",
 * });
 * export const id = sa.then(sa => sa.id);
 * export const dbId = sa.then(sa => sa.defaultDatabaseId);
 * ```
 */
export function getSqlLoginOutput(args: GetSqlLoginOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSqlLoginResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("mssql:index/getSqlLogin:getSqlLogin", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getSqlLogin.
 */
export interface GetSqlLoginOutputArgs {
    /**
     * Login name. Must follow [Regular Identifiers rules](https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers#rules-for-regular-identifiers) and cannot contain `\`
     */
    name: pulumi.Input<string>;
}
