// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * The provider type for the mssql package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'mssql';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Provider.__pulumiType;
    }

    /**
     * FQDN or IP address of the SQL endpoint. Can be also set using `MSSQL_HOSTNAME` environment variable.
     */
    public readonly hostname!: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["azureAuth"] = pulumi.output(args ? args.azureAuth : undefined).apply(JSON.stringify);
            resourceInputs["hostname"] = (args ? args.hostname : undefined) ?? utilities.getEnv("MSSQL_HOSTNAME");
            resourceInputs["port"] = pulumi.output((args ? args.port : undefined) ?? (utilities.getEnvNumber("MSSQL_PORT") || 1433)).apply(JSON.stringify);
            resourceInputs["sqlAuth"] = pulumi.output(args ? args.sqlAuth : undefined).apply(JSON.stringify);
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * When provided, Azure AD authentication will be used when connecting.
     */
    azureAuth?: pulumi.Input<inputs.ProviderAzureAuth>;
    /**
     * FQDN or IP address of the SQL endpoint. Can be also set using `MSSQL_HOSTNAME` environment variable.
     */
    hostname?: pulumi.Input<string>;
    /**
     * TCP port of SQL endpoint. Defaults to `1433`. Can be also set using `MSSQL_PORT` environment variable.
     */
    port?: pulumi.Input<number>;
    /**
     * When provided, SQL authentication will be used when connecting.
     */
    sqlAuth?: pulumi.Input<inputs.ProviderSqlAuth>;
}
